version: '3.6'
services:
  node_istanbul_1:
    image: quorum-2.5.0
    volumes:
      - './qdata_1:/qdata'
      - '/etc/localtime:/etc/localtime'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.2'
    ports:
      - 23001:8545
      - 24001:30303
      - 25001:50400
      - 26001:8546
      - 27001:9081
    user: '1000:1000'
  node_istanbul_2:
    image: quorum-2.5.0
    volumes:
      - './qdata_2:/qdata'
      - '/etc/localtime:/etc/localtime'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.3'
    ports:
      - 23002:8545
      - 24002:30303
      - 25002:50400
      - 26002:8546
      - 27002:9081
    user: '1000:1000'
  node_istanbul_3:
    image: quorum-2.5.0
    volumes:
      - './qdata_3:/qdata'
      - '/etc/localtime:/etc/localtime'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.4'
    ports:
      - 23003:8545
      - 24003:30303
      - 25003:50400
      - 26003:8546
      - 27003:9081
    user: '1000:1000'
  node_istanbul_4:
    image: quorum-2.5.0
    volumes:
      - './qdata_4:/qdata'
      - '/etc/localtime:/etc/localtime'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.5'
    ports:
      - 23004:8545
      - 24004:30303
      - 25004:50400
      - 26004:8546
      - 27004:9081
    user: '1000:1000'
  node_istanbul_5:
    image: quorum-2.5.0
    volumes:
      - './qdata_5:/qdata'
      - '/etc/localtime:/etc/localtime'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.6'
    ports:
      - 23005:8545
      - 24005:30303
      - 25005:50400
      - 26005:8546
      - 27005:9081
    user: '1000:1000'
networks:
  quorum_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16
