version: '3'

volumes:
  prometheus_data: {}
  grafana_storage: {}

services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - caliper_net

  ####################
  # CALIPER SERVICES #
  ####################

  caliper_master:
    container_name: caliper_master
    image: marcomazzoni/caliper-quorum:testing
    command: launch master --caliper-flow-skip-start --caliper-flow-skip-end
    environment:
      - CALIPER_BIND_SUT=quorum
      - CALIPER_BENCHCONFIG=benchconfig.yaml
      - CALIPER_NETWORKCONFIG=networkconfig.json
    volumes:
      - ~/Desktop/quorum-caliper-benchmarks/thesis/raft/private/4-nodes:/hyperledger/caliper/workspace
    depends_on:
      - mqtt_broker
    networks:
      - config_quorum_net
      - caliper_net

  caliper_worker_1:
    container_name: caliper_worker_1
    image: marcomazzoni/caliper-quorum:testing
    command: launch worker
    environment:
      - CALIPER_BIND_SUT=quorum
      - CALIPER_BENCHCONFIG=benchconfig.yaml
      - CALIPER_NETWORKCONFIG=networkconfig.json
    volumes:
      - ~/Desktop/quorum-caliper-benchmarks/thesis/raft/private/4-nodes:/hyperledger/caliper/workspace
    depends_on:
      - mqtt_broker
      - caliper_master
    networks:
      - config_quorum_net
      - caliper_net

  caliper_worker_2:
    container_name: caliper_worker_2
    image: marcomazzoni/caliper-quorum:testing
    command: launch worker
    environment:
      - CALIPER_BIND_SUT=quorum
      - CALIPER_BENCHCONFIG=benchconfig.yaml
      - CALIPER_NETWORKCONFIG=networkconfig.json
    volumes:
      - ~/Desktop/quorum-caliper-benchmarks/thesis/raft/private/4-nodes:/hyperledger/caliper/workspace
    depends_on:
      - mqtt_broker
      - caliper_master
    networks:
      - config_quorum_net
      - caliper_net

  caliper_worker_3:
    container_name: caliper_worker_3
    image: marcomazzoni/caliper-quorum:testing
    command: launch worker
    environment:
      - CALIPER_BIND_SUT=quorum
      - CALIPER_BENCHCONFIG=benchconfig.yaml
      - CALIPER_NETWORKCONFIG=networkconfig.json
    volumes:
      - ~/Desktop/quorum-caliper-benchmarks/thesis/raft/private/4-nodes:/hyperledger/caliper/workspace
    depends_on:
      - mqtt_broker
      - caliper_master
    networks:
      - config_quorum_net
      - caliper_net

  caliper_worker_4:
    container_name: caliper_worker_4
    image: marcomazzoni/caliper-quorum:testing
    command: launch worker
    environment:
      - CALIPER_BIND_SUT=quorum
      - CALIPER_BENCHCONFIG=benchconfig.yaml
      - CALIPER_NETWORKCONFIG=networkconfig.json
    volumes:
      - ~/Desktop/quorum-caliper-benchmarks/thesis/raft/private/4-nodes:/hyperledger/caliper/workspace
    depends_on:
      - mqtt_broker
      - caliper_master
    networks:
      - config_quorum_net
      - caliper_net


  ####################
  # MONITORING SERVICES #
  ####################

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus-quorum.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - caliper_net
      - config_quorum_net

  pushGateway:
    image: prom/pushgateway
    container_name: pushGateway
    ports:
      - '9091:9091'
    networks:
      - caliper_net
      - config_quorum_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: '104'
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    networks:
      - caliper_net
      - config_quorum_net

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: always
    networks:
      - caliper_net
      - config_quorum_net

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always
    networks:
      - caliper_net
      - config_quorum_net

networks:
  caliper_net:
    driver: bridge
  config_quorum_net:
    external: true
